name: multi-pipe
channels:
    - defaults
dependencies:
    - python=3.11
    - pip=23.3.1
    - pip:
          - ipykernel
          - ipywidgets
          - torch==2.1.2
          - torchvision==0.16.2
          - matplotlib==3.8.2
          - pyyaml==6.0.1
          - omegaconf==2.3.0
          - pandas==2.1.4
          - tensorboard==2.15.1
          - boto3==1.34.6
          - scikit-learn==1.3.2
          - seaborn==0.13.0
          - tqdm==4.66.1
          - timm==0.9.12
          - h5py
          - gdown
