name: mmcr
data:
    target: src.datasets.ConcatSet
    params:
        root:
            [./datasets/tea-std, ./datasets/tea-grade-v2, ./datasets/plant-doc]
        conf:
            [
                {
                    "target": "src.datasets.ClassDataset",
                    "split_mix": { "train": ["train"], "val": ["val", "test"] },
                },
                {
                    "target": "src.datasets.ClassDataset",
                    "split_mix": { "train": ["train"], "val": ["val", "test"] },
                },
                {
                    "target": "src.datasets.ClassDataset",
                    "split_mix": { "train": ["train"], "val": ["val", "test"] },
                    "params": { "resize_wh": [300, 300] },
                },
            ]
model:
    target: src.learners.BackBoneLearner
    params:
        enc_name: ResNet18
        enc_params:
            drop_out: 0.5
loss:
    target: src.losses.MMCRLoss
    params:
        lamb: 0.01
optimizer:
    target: torch.optim.AdamW
    params:
        lr: 1e-4
        betas: [0.9, 0.999]
        weight_decay: 3e-5
lr_scheduler:
    target: torch.optim.lr_scheduler.CosineAnnealingLR
    params:
        T_max: 10
        eta_min: 3e-8
train:
    loader_params:
        batch_size: 32
        num_workers: 3
        collate_fn:
            target: src.datasets.collate_fns.aug_collate_fn
            params:
                aug:
                    target: src.datasets.collate_fns.Augmentor
                    params:
                        crop_wh: [224, 224]
                aug_count: 20
    tollerance: -1
val:
    loader_params:
        batch_size: 32
        num_workers: 3
        collate_fn:
            target: src.datasets.collate_fns.aug_collate_fn
            params:
                aug:
                    target: src.datasets.collate_fns.Augmentor
                    params:
                        crop_wh: [224, 224]
                aug_count: 20
epochs: 100
checkpoints:
    - epoch: 10
      name: e10
    - epoch: 20
      name: e20
    - epoch: 30
      name: e30
    - epoch: 40
      name: e40
    - epoch: 50
      name: e50
    - epoch: 60
      name: e60
    - epoch: 70
      name: e70
    - epoch: 80
      name: e80
    - epoch: 90
      name: e90
    - epoch: 100
      name: e100
    - epoch: 110
      name: e110
    - epoch: 120
      name: e120
    - epoch: 130
      name: e130
    - epoch: 140
      name: e140
    - epoch: 150
      name: e150
    - epoch: 160
      name: e160
    - epoch: 170
      name: e170
    - epoch: 180
      name: e180
    - epoch: 190
      name: e190
