name: classify:resnet50
data:
    target: src.datasets.ClassDataset
    params:
        root: ./datasets/tea-grade-v2
model:
    target: src.learners.ClassifierLearner
    params:
        head_trail: [34]
        enc_name: ResNet50
        enc_params:
            drop_out: 0.2
        dec_params:
            drop_out: 0.2
            use_batch_norm: True
loss:
    target: src.losses.CrossEntropyLoss
    params:
        has_aug_ax: True
optimizer:
    target: torch.optim.AdamW
    params:
        lr: 1e-4
        betas: [0.9, 0.999]
        weight_decay: 3e-5
lr_scheduler:
    target: torch.optim.lr_scheduler.CosineAnnealingLR
    params:
        T_max: 15
        eta_min: 5e-8
train:
    loader_params:
        batch_size: 32
        num_workers: 2
        collate_fn:
            target: src.datasets.collate_fns.aug_collate_fn
            params:
                aug:
                    target: src.datasets.collate_fns.Augmentor
                    params:
                        crop_wh: [224, 224]
                aug_count: 6
    tollerance: 10
val:
    loader_params:
        batch_size: 32
        num_workers: 2
        collate_fn:
            target: src.datasets.collate_fns.aug_collate_fn
            params:
                aug:
                    target: src.datasets.collate_fns.Augmentor
                    params:
                        crop_wh: [224, 224]
                aug_count: 6
test:
    loader_params:
        batch_size: 64
        collate_fn:
            target: src.datasets.collate_fns.aug_collate_fn
            params:
                aug:
                    target: src.datasets.collate_fns.Augmentor
                    params:
                        crop_wh: [224, 224]
                        same: True
                aug_count: 1
    evaluators:
        classify:
            target: src.evaluators.ClassificationEvaluator
            params:
                has_aug_ax: True
epochs: 200
