name: mmcr:resnet50
data:
    target: src.datasets.ConcatSet
    params:
        root:
            [./datasets/tea-std, ./datasets/tea-grade-v2, ./datasets/plant-doc]
        conf:
            [
                {
                    "target": "src.datasets.ClassDataset",
                    "split_mix": { "train": ["train"], "val": ["val", "test"] },
                },
                {
                    "target": "src.datasets.ClassDataset",
                    "split_mix": { "train": ["train"], "val": ["val", "test"] },
                },
                {
                    "target": "src.datasets.ClassDataset",
                    "split_mix": { "train": ["train"], "val": ["val", "test"] },
                    "params": { "resize_wh": [300, 300] },
                },
            ]
model:
    target: src.learners.BackBoneLearner
    params:
        enc_name: ResNet50
        enc_params:
            drop_out: 0.2
loss:
    target: src.losses.MMCRLoss
    params:
        lamb: 0.01
optimizer:
    target: torch.optim.AdamW
    params:
        lr: 1e-4
        betas: [0.9, 0.999]
        weight_decay: 3e-5
lr_scheduler:
    target: torch.optim.lr_scheduler.CosineAnnealingLR
    params:
        T_max: 15
        eta_min: 5e-16
train:
    loader_params:
        batch_size: 32
        num_workers: 2
        collate_fn:
            target: src.datasets.collate_fns.aug_collate_fn
            params:
                aug:
                    target: src.datasets.collate_fns.Augmentor
                    params:
                        crop_wh: [224, 224]
                aug_count: 6
    tollerance: 10
val:
    loader_params:
        batch_size: 32
        num_workers: 2
        collate_fn:
            target: src.datasets.collate_fns.aug_collate_fn
            params:
                aug:
                    target: src.datasets.collate_fns.Augmentor
                    params:
                        crop_wh: [224, 224]
                aug_count: 6
epochs: 200
